author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /test_annotations
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    deep_zoom: true
    extra_js:
    - openseadragon.min.js
    - openseadragon-svg-overlay.js
    - text-annotations.js
    - viewer.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://iip.readux.io/iiif/2/2r3hrw04_Origin-1911-a-0001.tif/full/full/0/default.jpg
image_size:
  page:
    height: 4427
    width: 3557
permalink: pretty
publication_info:
  date: '2023'
  editors: []
  title: 'Original sacred harp : containing a superior collection of standard melodies,
    of odes, anthems, and church music, and hymns of high repute'
show_annotation_author: true
source_info:
  title: 'Original sacred harp : containing a superior collection of standard melodies,
    of odes, anthems, and church music, and hymns of high repute'
  via_readux: true
tagline: an annotated digital edition
title: 'Original sacred harp : containing a superior collection of standard melodies,
  of odes, anthems, and church music, and hymns of high repute'
url: https://etowsif.github.io
version: 0.7
